In [6]:
import numpy as np
import pandas as pd
import sqlite3

In [7]:
lang_agegp=pd.read_csv("multilingual-age.csv")
data_lang_edu=pd.read_csv("multilingual-education.csv")
data_agegp_edu=pd.read_csv("age-education.csv")

In [8]:
data_agegp_edu.columns=['a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18','a19','a20','a21','a22','a23','a24','a25','a26','a27','a28','a29','a30','a31','a32','a33','a34','a35','a36','a37','a38','a39','a40','a41','a42','a43','a44','a45']
lang_agegp.columns=['b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'b10', 'b11']
data_lang_edu.columns=['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11']

In [10]:
data_agegp_edu.drop([0,1,2,3,4,5],inplace=True)
lang_agegp.drop([0,1,2,3],inplace=True)
data_lang_edu.drop([0,1,2,3],inplace=True)

In [13]:
conn = sqlite3.connect('population6.db')
c = conn.cursor()
data_agegp_edu.to_sql('agegp_edu',conn,if_exists='append', index=False)
data_lang_agegp.to_sql('lang_agegp',conn,if_exists='append', index=False)
data_lang_edu.to_sql('lang_edu',conn,if_exists='append', index=False)

In [14]:
data_agegp_edu

,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,...,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45
6,C2308,00,000,INDIA,Total,All ages,1210854977,623270258,587584719,447216165,...,345724,7238719,5354161,1884558,68288971,42120460,26168511,3031570,1647116,1384454
7,C2308,00,000,INDIA,Total,0-6,164515253,85752254,78762999,164515253,...,0,0,0,0,0,0,0,0,0,0
8,C2308,00,000,INDIA,Total,7,24826640,12903364,11923276,6748214,...,0,0,0,0,0,0,0,136465,75715,60750
9,C2308,00,000,INDIA,Total,8,26968373,14061937,12906436,4131414,...,0,0,0,0,0,0,0,96524,52561,43963
10,C2308,00,000,INDIA,Total,9,23424638,12214985,11209653,2491904,...,0,0,0,0,0,0,0,70452,38456,31996
11,C2308,00,000,INDIA,Total,10,30552107,16089436,14462671,3454505,...,0,0,0,0,0,0,0,85652,47423,38229
12,C2308,00,000,INDIA,Total,11,24740946,12962604,11778342,1988473,...,0,0,0,0,0,0,0,65030,35877,29153
13,C2308,00,000,INDIA,Total,12,27877307,14637892,13239415,2391529,...,0,0,0,0,0,0,0,68452,37773,30679
14,C2308,00,000,INDIA,Total,13,24280683,12563775,11716908,1810476,...,0,0,0,0,0,0,0,56720,30680,26040
15,C2308,00,000,INDIA,Total,14,25258169,13165128,12093041,2100785,...,0,0,0,0,0,0,0,58561,31901,26660
16,C2308,00,000,INDIA,Total,15,25899454,13739746,12159708,2599957,...,0,0,0,0,0,0,0,62039,34656,27383
17,C2308,00,000,INDIA,Total,16,24592293,13027935,11564358,2512487,...,0,0,0,0,0,0,0,60587,33777,26810
18,C2308,00,000,INDIA,Total,17,21217467,11349449,9868018,2038455,...,0,0,0,0,0,0,0,53520,30035,23485
19,C2308,00,000,INDIA,Total,18,27958147,15020851,12937296,3727975,...,19726,374081,271491,102590,0,0,0,69648,39697,29951
20,C2308,00,000,INDIA,Total,19,20859088,10844415,10014673,2578674,...,17178,415931,293517,122414,0,0,0,54079,29839,24240
21,C2308,00,000,INDIA,Total,20-24,111424222,57584693,53839529,18679492,...,76240,1888379,1322758,565621,13170028,7029489,6140539,283366,156685,126681
22,C2308,00,000,INDIA,Total,25-29,101413965,51344208,50069757,22634440,...,54424,1086833,791159,295674,14119774,7903752,6216022,257195,139917,117278
23,C2308,00,000,INDIA,Total,30-34,88594951,44660674,43934277,24329560,...,41306,794050,611483,182567,10341988,6112575,4229413,230611,125521,105090
24,C2308,00,000,INDIA,Total,35-39,85140684,42919381,42221303,27863127,...,35083,643622,503759,139863,8173370,5121959,3051411,229647,124135,105512
25,C2308,00,000,INDIA,Total,40-44,72438112,37545386,34892726,26806872,...,26383,538607,424028,114579,6326586,4202356,2124230,205514,113831,91683
26,C2308,00,000,INDIA,Total,45-49,62318327,32138114,30180213,25077763,...,18919,400572,316960,83612,4919451,3395939,1523512,180091,97709,82382
27,C2308,00,000,INDIA,Total,50-54,49069254,25843266,23225988,20822208,...,14173,287751,226550,61201,3694020,2628625,1065395,146056,80148,65908
28,C2308,00,000,INDIA,Total,55-59,39146055,19456012,19690043,17682081,...,12659,226205,174092,52113,2868480,2120540,747940,119010,61283,57727
29,C2308,00,000,INDIA,Total,60-64,37663707,18701749,18961958,19989439,...,10652,213973,152936,61037,1973967,1514324,459643,124916,64823,60093
30,C2308,00,000,INDIA,Total,65-69,26454983,12944326,13510657,14829607,...,6974,162259,118515,43744,1089553,864263,225290,99287,49874,49413
31,C2308,00,000,INDIA,Total,70-74,19208842,9651499,9557343,11568624,...,4912,103000,74267,28733,661941,535931,126010,77511,40266,37245
32,C2308,00,000,INDIA,Total,75-79,9232503,4490603,4741900,5361192,...,2671,48614,33716,14898,327998,268932,59066,39626,19682,19944
33,C2308,00,000,INDIA,Total,80+,11289005,5283695,6005310,6890447,...,2798,36432,24942,11490,339629,250257,89372,52529,25790,26739
34,C2308,00,000,INDIA,Total,Age not stated,4489802,2372881,2116921,1591212,...,1626,18410,13988,4422,282186,171518,110668,48482,29062,19420
35,C2308,00,000,INDIA,Rural,All ages,833748852,427781058,405967794,350955017,...,146694,3069181,2285580,783601,22339967,15659295,6680672,2057684,1135912,921772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3108,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Rural,Age not stated,180,101,79,38,...,0,2,2,0,6,5,1,4,3,1
3109,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,All ages,143488,76584,66904,27232,...,83,2888,1707,1181,15201,8287,6914,313,161,152
3110,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,0-6,14463,7400,7063,14463,...,0,0,0,0,0,0,0,0,0,0
3111,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,7,2299,1147,1152,256,...,0,0,0,0,0,0,0,27,16,11
3112,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,8,2217,1134,1083,71,...,0,0,0,0,0,0,0,7,4,3
3113,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,9,2289,1154,1135,80,...,0,0,0,0,0,0,0,6,4,2
3114,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,10,2615,1337,1278,89,...,0,0,0,0,0,0,0,4,2,2
3115,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,11,2555,1342,1213,47,...,0,0,0,0,0,0,0,5,2,3
3116,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,12,2378,1227,1151,22,...,0,0,0,0,0,0,0,2,1,1
3117,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,13,2326,1252,1074,26,...,0,0,0,0,0,0,0,2,0,2
3118,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,14,2367,1229,1138,26,...,0,0,0,0,0,0,0,0,0,0
3119,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,15,2559,1304,1255,38,...,0,0,0,0,0,0,0,3,3,0
3120,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,16,2489,1292,1197,29,...,0,0,0,0,0,0,0,0,0,0
3121,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,17,2478,1326,1152,25,...,0,0,0,0,0,0,0,4,4,0
3122,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,18,2588,1359,1229,65,...,3,73,37,36,0,0,0,1,0,1
3123,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,19,2543,1341,1202,75,...,4,95,38,57,0,0,0,3,3,0
3124,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,20-24,14575,7874,6701,523,...,17,608,322,286,2173,966,1207,31,20,11
3125,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,25-29,16164,8555,7609,875,...,15,465,249,216,3252,1626,1626,27,13,14
3126,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,30-34,13912,7414,6498,956,...,11,411,244,167,2545,1318,1227,17,12,5
3127,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,35-39,13040,6746,6294,1394,...,11,302,173,129,2098,1110,988,26,12,14
3128,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,40-44,10776,5892,4884,1501,...,10,301,210,91,1910,1083,827,23,13,10
3129,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,45-49,9429,5279,4150,1644,...,2,277,208,69,1352,836,516,28,14,14
3130,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,50-54,6621,3723,2898,1329,...,3,149,98,51,892,603,289,24,8,16
3131,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,55-59,5132,2981,2151,1160,...,2,119,72,47,556,417,139,28,12,16
3132,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,60-64,3274,1908,1366,999,...,1,41,27,14,226,178,48,18,7,11
3133,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,65-69,1757,953,804,586,...,0,21,14,7,82,72,10,4,1,3
3134,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,70-74,1193,691,502,419,...,4,14,9,5,56,41,15,7,4,3
3135,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,75-79,645,343,302,234,...,0,6,3,3,22,16,6,7,4,3
3136,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,80+,616,287,329,264,...,0,2,1,1,23,14,9,6,1,5
3137,C2308,35,000,State - ANDAMAN & NICOBAR ISLANDS,Urban,Age not stated,188,94,94,36,...,0,4,2,2,14,7,7,3,1,2

,b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11
4,00,00,INDIA,Total,Total,314988770,176696383,138292387,86009580,50536832,35472748
5,00,00,INDIA,Total,5-9,15649192,8166843,7482349,1844108,978151,865957
6,00,00,INDIA,Total,10-14,34488492,18133423,16355069,7254335,3831131,3423204
7,00,00,INDIA,Total,15-19,42424599,22750908,19673691,12626717,6792766,5833951
8,00,00,INDIA,Total,20-24,41344406,22386694,18957712,12834334,7067614,5766720
9,00,00,INDIA,Total,25-29,35924045,19695033,16229012,10857171,6144045,4713126
10,00,00,INDIA,Total,30-49,96443870,55866320,40577550,27466884,16824473,10642411
11,00,00,INDIA,Total,50-69,39729782,24306735,15423047,10916361,7385967,3530394
12,00,00,INDIA,Total,70+,7962347,4813671,3148676,1954539,1362695,591844
13,00,00,INDIA,Total,Age not stated,1022037,576756,445281,255131,149990,105141
14,00,00,INDIA,Rural,Total,162641485,92988052,69653433,35383989,21771062,13612927
15,00,00,INDIA,Rural,5-9,9292251,4815380,4476871,672498,356376,316122
16,00,00,INDIA,Rural,10-14,20960599,11005994,9954605,3638873,1929573,1709300
17,00,00,INDIA,Rural,15-19,24547666,13342296,11205370,6559688,3616092,2943596
18,00,00,INDIA,Rural,20-24,21905564,12180144,9725420,5966021,3449951,2516070
19,00,00,INDIA,Rural,25-29,18052954,10261185,7791769,4569413,2768678,1800735
20,00,00,INDIA,Rural,30-49,45973742,27687500,18286242,10139312,6778161,3361151
21,00,00,INDIA,Rural,50-69,17824491,11195472,6629019,3215504,2413157,802347
22,00,00,INDIA,Rural,70+,3635989,2240389,1395600,534536,404113,130423
23,00,00,INDIA,Rural,Age not stated,448229,259692,188537,88144,54961,33183
24,00,00,INDIA,Urban,Total,152347285,83708331,68638954,50625591,28765770,21859821
25,00,00,INDIA,Urban,5-9,6356941,3351463,3005478,1171610,621775,549835
26,00,00,INDIA,Urban,10-14,13527893,7127429,6400464,3615462,1901558,1713904
27,00,00,INDIA,Urban,15-19,17876933,9408612,8468321,6067029,3176674,2890355
28,00,00,INDIA,Urban,20-24,19438842,10206550,9232292,6868313,3617663,3250650
29,00,00,INDIA,Urban,25-29,17871091,9433848,8437243,6287758,3375367,2912391
30,00,00,INDIA,Urban,30-49,50470128,28178820,22291308,17327572,10046312,7281260
31,00,00,INDIA,Urban,50-69,21905291,13111263,8794028,7700857,4972810,2728047
32,00,00,INDIA,Urban,70+,4326358,2573282,1753076,1420003,958582,461421
33,00,00,INDIA,Urban,Age not stated,573808,317064,256744,166987,95029,71958
...,...,...,...,...,...,...,...,...,...,...,...
1054,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Total,257425,142378,115047,72708,41846,30862
1055,35,00,ANDAMAN & NICOBAR ISLANDS,Total,5-9,14096,7110,6986,1958,983,975
1056,35,00,ANDAMAN & NICOBAR ISLANDS,Total,10-14,25476,12995,12481,6651,3331,3320
1057,35,00,ANDAMAN & NICOBAR ISLANDS,Total,15-19,26857,14005,12852,9494,4785,4709
1058,35,00,ANDAMAN & NICOBAR ISLANDS,Total,20-24,29179,15535,13644,9171,4827,4344
1059,35,00,ANDAMAN & NICOBAR ISLANDS,Total,25-29,32609,17622,14987,9716,5320,4396
1060,35,00,ANDAMAN & NICOBAR ISLANDS,Total,30-49,91903,51816,40087,27080,16469,10611
1061,35,00,ANDAMAN & NICOBAR ISLANDS,Total,50-69,32357,20054,12303,7803,5517,2286
1062,35,00,ANDAMAN & NICOBAR ISLANDS,Total,70+,4721,3115,1606,771,579,192
1063,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Age not stated,227,126,101,64,35,29
1064,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Total,152600,84758,67842,38136,22243,15893
1065,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,5-9,7941,4012,3929,939,474,465
1066,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,10-14,15529,7852,7677,3667,1814,1853
1067,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,15-19,16182,8449,7733,5334,2719,2615
1068,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,20-24,17279,9014,8265,5093,2661,2432
1069,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,25-29,19544,10610,8934,5352,2965,2387
1070,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,30-49,53497,30515,22982,13760,8645,5115
1071,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,50-69,19458,12151,7307,3626,2675,951
1072,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,70+,3077,2099,978,339,274,65
1073,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Age not stated,93,56,37,26,16,10
1074,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Total,104825,57620,47205,34572,19603,14969
1075,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,5-9,6155,3098,3057,1019,509,510
1076,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,10-14,9947,5143,4804,2984,1517,1467
1077,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,15-19,10675,5556,5119,4160,2066,2094
1078,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,20-24,11900,6521,5379,4078,2166,1912
1079,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,25-29,13065,7012,6053,4364,2355,2009
1080,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,30-49,38406,21301,17105,13320,7824,5496
1081,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,50-69,12899,7903,4996,4177,2842,1335
1082,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,70+,1644,1016,628,432,305,127
1083,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Age not stated,134,70,64,38,19,19

,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11
4,00,00,INDIA,Total,Total,314988770,176696383,138292387,86009580,50536832,35472748
5,00,00,INDIA,Total,Illiterate,42266268,17851584,24414684,3879858,1890285,1989573
6,00,00,INDIA,Total,Literate,272722502,158844799,113877703,82129722,48646547,33483175
7,00,00,INDIA,Total,Literate but below primary,29345104,16126959,13218145,3733616,2108024,1625592
8,00,00,INDIA,Total,Primary but below middle,48570544,26588496,21982048,8636296,4782211,3854085
9,00,00,INDIA,Total,Middle but below matric/secondary,43116661,25214857,17901804,10743350,6266289,4477061
10,00,00,INDIA,Total,Matric/Secondary but below graduate,93204075,56022449,37181626,33899219,20411147,13488072
11,00,00,INDIA,Total,Graduate and above,46958049,28285620,18672429,22146543,13316422,8830121
12,00,00,INDIA,Rural,Total,162641485,92988052,69653433,35383989,21771062,13612927
13,00,00,INDIA,Rural,Illiterate,30204008,12774715,17429293,2234076,1105619,1128457
14,00,00,INDIA,Rural,Literate,132437477,80213337,52224140,33149913,20665443,12484470
15,00,00,INDIA,Rural,Literate but below primary,18487727,10353027,8134700,1750972,1033945,717027
16,00,00,INDIA,Rural,Primary but below middle,28926164,16345445,12580719,4499137,2578263,1920874
17,00,00,INDIA,Rural,Middle but below matric/secondary,24957847,15068362,9889485,6010075,3608166,2401909
18,00,00,INDIA,Rural,Matric/Secondary but below graduate,42300193,26798111,15502082,14549061,9185784,5363277
19,00,00,INDIA,Rural,Graduate and above,11762090,8062603,3699487,5090441,3470061,1620380
20,00,00,INDIA,Urban,Total,152347285,83708331,68638954,50625591,28765770,21859821
21,00,00,INDIA,Urban,Illiterate,12062260,5076869,6985391,1645782,784666,861116
22,00,00,INDIA,Urban,Literate,140285025,78631462,61653563,48979809,27981104,20998705
23,00,00,INDIA,Urban,Literate but below primary,10857377,5773932,5083445,1982644,1074079,908565
24,00,00,INDIA,Urban,Primary but below middle,19644380,10243051,9401329,4137159,2203948,1933211
25,00,00,INDIA,Urban,Middle but below matric/secondary,18158814,10146495,8012319,4733275,2658123,2075152
26,00,00,INDIA,Urban,Matric/Secondary but below graduate,50903882,29224338,21679544,19350158,11225363,8124795
27,00,00,INDIA,Urban,Graduate and above,35195959,20223017,14972942,17056102,9846361,7209741
28,01,00,JAMMU & KASHMIR,Total,Total,6183190,3634819,2548371,2096220,1258756,837464
29,01,00,JAMMU & KASHMIR,Total,Illiterate,764675,343219,421456,132783,62798,69985
30,01,00,JAMMU & KASHMIR,Total,Literate,5418515,3291600,2126915,1963437,1195958,767479
31,01,00,JAMMU & KASHMIR,Total,Literate but below primary,569135,316283,252852,102814,57593,45221
32,01,00,JAMMU & KASHMIR,Total,Primary but below middle,935821,529413,406408,196414,113132,83282
33,01,00,JAMMU & KASHMIR,Total,Middle but below matric/secondary,1331807,817811,513996,348840,214671,134169
...,...,...,...,...,...,...,...,...,...,...,...
838,34,00,PUDUCHERRY,Urban,Literate,305959,166055,139904,66004,37349,28655
839,34,00,PUDUCHERRY,Urban,Literate but below primary,10410,5263,5147,1519,804,715
840,34,00,PUDUCHERRY,Urban,Primary but below middle,23189,11582,11607,3312,1730,1582
841,34,00,PUDUCHERRY,Urban,Middle but below matric/secondary,31149,15786,15363,4815,2657,2158
842,34,00,PUDUCHERRY,Urban,Matric/Secondary but below graduate,130935,72023,58912,26146,14929,11217
843,34,00,PUDUCHERRY,Urban,Graduate and above,103179,57768,45411,28498,16321,12177
844,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Total,257425,142378,115047,72708,41846,30862
845,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Illiterate,24532,10752,13780,1434,669,765
846,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Literate,232893,131626,101267,71274,41177,30097
847,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Literate but below primary,28256,15471,12785,3567,1936,1631
848,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Primary but below middle,52437,29491,22946,8570,4836,3734
849,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Middle but below matric/secondary,54940,31737,23203,13994,8315,5679
850,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Matric/Secondary but below graduate,70904,40105,30799,30717,17637,13080
851,35,00,ANDAMAN & NICOBAR ISLANDS,Total,Graduate and above,21773,12380,9393,13335,7817,5518
852,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Total,152600,84758,67842,38136,22243,15893
853,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Illiterate,15568,6933,8635,660,315,345
854,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Literate,137032,77825,59207,37476,21928,15548
855,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Literate but below primary,18623,10346,8277,1879,1019,860
856,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Primary but below middle,34872,19599,15273,5175,2931,2244
857,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Middle but below matric/secondary,35450,20325,15125,8738,5153,3585
858,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Matric/Secondary but below graduate,37299,21243,16056,15900,9255,6645
859,35,00,ANDAMAN & NICOBAR ISLANDS,Rural,Graduate and above,8136,4888,3248,5246,3258,1988
860,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Total,104825,57620,47205,34572,19603,14969
861,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Illiterate,8964,3819,5145,774,354,420
862,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Literate,95861,53801,42060,33798,19249,14549
863,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Literate but below primary,9633,5125,4508,1688,917,771
864,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Primary but below middle,17565,9892,7673,3395,1905,1490
865,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Middle but below matric/secondary,19490,11412,8078,5256,3162,2094
866,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Matric/Secondary but below graduate,33605,18862,14743,14817,8382,6435
867,35,00,ANDAMAN & NICOBAR ISLANDS,Urban,Graduate and above,13637,7492,6145,8089,4559,3530